# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

###### Default build via devtools::use_travis()

language: r
sudo: false
cache: packages

###### Custom Options

# Containers have 2 CPUs by default. Speed up the build by using both.
# c.f. https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system
env:
  global:
  - MAKEFLAGS="-j 2"
  - _R_CHECK_FORCE_SUGGESTS_=false

# Run R package on both release and developer versions
jobs:
  include:
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
    before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
  - r: devel
  - r: oldrel

# If one fails, avoid running the other.
matrix:
  fast_finish: true

