// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rmultinomial
double rmultinomial(const arma::vec& ps);
RcppExport SEXP dina_rmultinomial(SEXP psSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type ps(psSEXP);
    __result = Rcpp::wrap(rmultinomial(ps));
    return __result;
END_RCPP
}
// rDirichlet
arma::vec rDirichlet(const arma::vec& deltas);
RcppExport SEXP dina_rDirichlet(SEXP deltasSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::vec& >::type deltas(deltasSEXP);
    __result = Rcpp::wrap(rDirichlet(deltas));
    return __result;
END_RCPP
}
// DINAsim
Rcpp::List DINAsim(const arma::mat& alphas, const arma::mat& Q, const arma::vec& ss, const arma::vec& gs);
RcppExport SEXP dina_DINAsim(SEXP alphasSEXP, SEXP QSEXP, SEXP ssSEXP, SEXP gsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type alphas(alphasSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ss(ssSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gs(gsSEXP);
    __result = Rcpp::wrap(DINAsim(alphas, Q, ss, gs));
    return __result;
END_RCPP
}
// update_alpha
Rcpp::List update_alpha(const arma::mat& Amat, const arma::mat& Q, const arma::vec& ss, const arma::vec& gs, const arma::mat& Y, const arma::vec& PIs, arma::mat& ALPHAS, const arma::vec& delta0);
RcppExport SEXP dina_update_alpha(SEXP AmatSEXP, SEXP QSEXP, SEXP ssSEXP, SEXP gsSEXP, SEXP YSEXP, SEXP PIsSEXP, SEXP ALPHASSEXP, SEXP delta0SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type Amat(AmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ss(ssSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gs(gsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type PIs(PIsSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type ALPHAS(ALPHASSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta0(delta0SEXP);
    __result = Rcpp::wrap(update_alpha(Amat, Q, ss, gs, Y, PIs, ALPHAS, delta0));
    return __result;
END_RCPP
}
// update_sg
Rcpp::List update_sg(const arma::mat& Y, const arma::mat& Q, const arma::mat& ALPHAS, const arma::vec& ss_old, double as0, double bs0, double ag0, double bg0);
RcppExport SEXP dina_update_sg(SEXP YSEXP, SEXP QSEXP, SEXP ALPHASSEXP, SEXP ss_oldSEXP, SEXP as0SEXP, SEXP bs0SEXP, SEXP ag0SEXP, SEXP bg0SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ALPHAS(ALPHASSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ss_old(ss_oldSEXP);
    Rcpp::traits::input_parameter< double >::type as0(as0SEXP);
    Rcpp::traits::input_parameter< double >::type bs0(bs0SEXP);
    Rcpp::traits::input_parameter< double >::type ag0(ag0SEXP);
    Rcpp::traits::input_parameter< double >::type bg0(bg0SEXP);
    __result = Rcpp::wrap(update_sg(Y, Q, ALPHAS, ss_old, as0, bs0, ag0, bg0));
    return __result;
END_RCPP
}
// DINA_Gibbs
Rcpp::List DINA_Gibbs(const arma::mat& Y, const arma::mat& Amat, const arma::mat& Q, unsigned int chain_length);
RcppExport SEXP dina_DINA_Gibbs(SEXP YSEXP, SEXP AmatSEXP, SEXP QSEXP, SEXP chain_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Amat(AmatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type chain_length(chain_lengthSEXP);
    __result = Rcpp::wrap(DINA_Gibbs(Y, Amat, Q, chain_length));
    return __result;
END_RCPP
}
